apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "yolo"
  namespace: oscar-svc
spec:
  predictor:
    serviceAccountName: minio-sa
    model:
      protocolVersion: v1
      modelFormat:
        name: tensorflow
      storageUri: "s3://kserve-models/tf"
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi