alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: true

pushgateway:
  enabled: false

kubelet:
  enabled: true
  serviceMonitor:
    cAdvisor: true

prometheus:
  enabled: true
  service:
    type: ClusterIP
  prometheusSpec:
    scrapeInterval: 2m
    scrapeTimeout: 5s
    evaluationInterval: 1m
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: "10Gi"
    additionalScrapeConfigs:
      - job_name: kubernetes-nodes
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: kubelet_volume_stats_used_bytes|kubelet_volume_stats_capacity_bytes
            action: keep
          - source_labels: [namespace]
            regex: monitoring
            action: keep
          - source_labels: [persistentvolumeclaim]
            regex: prometheus-server|storage-loki-0
            action: keep
          - action: labeldrop
            regex: (instance|node|job)
      - job_name: kubernetes-nodes-cadvisor
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: container_cpu_usage_seconds_total|container_gpu_usage_seconds_total
            action: keep
          - source_labels: [namespace]
            regex: oscar-svc.*
            action: keep
          - source_labels: [pod]
            regex: ^(.+)-dlp-[a-z0-9]{9,}-[a-z0-9]{5}$
            target_label: service
            replacement: $1
            action: replace
          - source_labels: [pod]
            regex: ^(.+?)(?:-[0-9]{5}-deployment)?-[a-z0-9]{9,}-[a-z0-9]{5}$
            target_label: service
            replacement: $1
            action: replace
          - action: labeldrop
            regex: (image|id|name|instance|node|pod)