linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  prealloc:
    skip-var-check: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gocyclo
    - gofmt
    - goheader
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - misspell

run:
  timeout: 5m
  modules-download-mode: readonly
