
from __future__ import absolute_import
from swagger_server.models.base_model_ import Model
from swagger_server import util


class DeleteFunctionRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, delete_buckets: bool=None):  # noqa: E501
        """DeleteFunctionRequest - a model defined in Swagger

        :param name: The name of this DeleteFunctionRequest.  # noqa: E501
        :type name: str
        :param delete_buckets: The delete_buckets of this DeleteFunctionRequest.  # noqa: E501
        :type delete_buckets: bool
        """
        self.swagger_types = {
            'name': str,
            'delete_buckets': bool
        }

        self.attribute_map = {
            'name': 'name',
            'delete_buckets': 'deleteBuckets'
        }

        self._name = name
        self._delete_buckets = delete_buckets

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteFunctionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteFunctionRequest of this DeleteFunctionRequest.  # noqa: E501
        :rtype: DeleteFunctionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this DeleteFunctionRequest.

        Name of deployed function  # noqa: E501

        :return: The name of this DeleteFunctionRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DeleteFunctionRequest.

        Name of deployed function  # noqa: E501

        :param name: The name of this DeleteFunctionRequest.
        :type name: str
        """

        self._name = name

    @property
    def delete_buckets(self) -> bool:
        """Gets the delete_buckets of this DeleteFunctionRequest.

        Delete linked buckets  # noqa: E501

        :return: The delete_buckets of this DeleteFunctionRequest.
        :rtype: bool
        """
        return self._delete_buckets

    @delete_buckets.setter
    def delete_buckets(self, delete_buckets: bool):
        """Sets the delete_buckets of this DeleteFunctionRequest.

        Delete linked buckets  # noqa: E501

        :param delete_buckets: The delete_buckets of this DeleteFunctionRequest.
        :type delete_buckets: bool
        """

        self._delete_buckets = delete_buckets
