# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DeleteFunctionRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, function_name: str=None):  # noqa: E501
        """DeleteFunctionRequest - a model defined in Swagger

        :param function_name: The function_name of this DeleteFunctionRequest.  # noqa: E501
        :type function_name: str
        """
        self.swagger_types = {
            'function_name': str
        }

        self.attribute_map = {
            'function_name': 'functionName'
        }

        self._function_name = function_name

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteFunctionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteFunctionRequest of this DeleteFunctionRequest.  # noqa: E501
        :rtype: DeleteFunctionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def function_name(self) -> str:
        """Gets the function_name of this DeleteFunctionRequest.

        Name of deployed function  # noqa: E501

        :return: The function_name of this DeleteFunctionRequest.
        :rtype: str
        """
        return self._function_name

    @function_name.setter
    def function_name(self, function_name: str):
        """Sets the function_name of this DeleteFunctionRequest.

        Name of deployed function  # noqa: E501

        :param function_name: The function_name of this DeleteFunctionRequest.
        :type function_name: str
        """
        if function_name is None:
            raise ValueError("Invalid value for `function_name`, must not be `None`")  # noqa: E501

        self._function_name = function_name
