from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """InBody - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'InBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InBody of this InBody.  # noqa: E501
        :rtype: InBody
        """
        return util.deserialize_model(dikt, cls)
