apiVersion: v1
kind: Pod
metadata:
  name: geoip-loader
  namespace: monitoring
spec:
  restartPolicy: Never
  containers:
    - name: loader
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: geoip-db
          mountPath: /var/lib/geoip
  volumes:
    - name: geoip-db
      persistentVolumeClaim:
        claimName: geoip-db
