apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoip-db
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
