openapi: 3.0.3
info:
  title: OSCAR Metrics Reporting
  version: 1.2.0
paths:
  /system/metrics/{serviceName}:
    get:
      summary: Get a single metric value for a service and time range
      parameters:
        - name: serviceName
          in: path
          required: true
          schema:
            type: string
        - name: metric
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/MetricKey"
          description: If omitted, returns all supported per-service metrics.
        - name: start
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Defaults to 24 hours before end (or now) if omitted.
        - name: end
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Defaults to now if omitted.
      responses:
        "200":
          description: Metric value
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/MetricValue"
                  - $ref: "#/components/schemas/ServiceMetrics"
        "400":
          description: Invalid parameters
        "500":
          description: Metrics computation failed
  /system/metrics:
    get:
      summary: Get metrics summary for a time range
      parameters:
        - name: start
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Defaults to 24 hours before end (or now) if omitted.
        - name: end
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Defaults to now if omitted.
      responses:
        "200":
          description: Metrics summary
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MetricsSummary"
        "400":
          description: Invalid time range
        "500":
          description: Metrics computation failed
  /system/metrics/breakdown:
    get:
      summary: Get metrics breakdown by dimension
      parameters:
        - name: start
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Defaults to 24 hours before end (or now) if omitted.
        - name: end
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Defaults to now if omitted.
        - name: group_by
          in: query
          required: true
          schema:
            type: string
            enum: [service, user, country]
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum: [json, csv]
            default: json
        - name: include_users
          in: query
          required: false
          schema:
            type: boolean
            default: false
          description: When true and group_by=service, include the list of users (JSON only).
      responses:
        "200":
          description: Metrics breakdown
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MetricsBreakdown"
            text/csv:
              schema:
                type: string
        "400":
          description: Invalid parameters
        "500":
          description: Metrics computation failed
components:
  schemas:
    MetricValue:
      type: object
      required: [service_id, metric, start, end, value, sources]
      properties:
        service_id:
          type: string
        metric:
          $ref: "#/components/schemas/MetricKey"
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        value:
          type: number
        unit:
          type: string
        sources:
          type: array
          items:
            $ref: "#/components/schemas/SourceStatus"
    ServiceMetrics:
      type: object
      required: [service_name, start, end, metrics]
      properties:
        service_name:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        metrics:
          type: array
          items:
            $ref: "#/components/schemas/ServiceMetricValue"
    ServiceMetricValue:
      type: object
      required: [metric, value, sources]
      properties:
        metric:
          $ref: "#/components/schemas/MetricKey"
        value:
          type: number
        unit:
          type: string
        sources:
          type: array
          items:
            $ref: "#/components/schemas/SourceStatus"
    MetricsSummary:
      type: object
      required: [start, end, totals, sources]
      properties:
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        totals:
          type: object
          required:
            - services_count_active
            - services_count_total
            - cpu_hours_total
            - gpu_hours_total
            - requests_count_total
            - requests_count_sync
            - requests_count_async
            - requests_count_exposed
            - countries_count
            - countries
            - users_count
            - users
          properties:
            services_count_active:
              type: integer
              minimum: 0
            services_count_total:
              type: integer
              minimum: 0
            cpu_hours_total:
              type: number
              minimum: 0
            gpu_hours_total:
              type: number
              minimum: 0
            requests_count_total:
              type: integer
              minimum: 0
            requests_count_sync:
              type: integer
              minimum: 0
            requests_count_async:
              type: integer
              minimum: 0
            requests_count_exposed:
              type: integer
              minimum: 0
            countries_count:
              type: integer
              minimum: 0
            countries:
              type: array
              items:
                $ref: "#/components/schemas/CountryCount"
            users_count:
              type: integer
              minimum: 0
            users:
              type: array
              items:
                type: string
        sources:
          type: array
          items:
            $ref: "#/components/schemas/SourceStatus"
    MetricsBreakdown:
      type: object
      required: [start, end, group_by, items]
      properties:
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        group_by:
          type: string
          enum: [service, user, country]
        items:
          type: array
          items:
            $ref: "#/components/schemas/BreakdownItem"
    BreakdownItem:
      type: object
      required: [key, countries]
      properties:
        key:
          type: string
        membership:
          type: string
          enum: [member, external, unknown]
        executions_count:
          type: integer
          minimum: 0
          description: Omitted when group_by=service.
        requests_count_total:
          type: integer
          minimum: 0
        requests_count_sync:
          type: integer
          minimum: 0
        requests_count_async:
          type: integer
          minimum: 0
        requests_count_exposed:
          type: integer
          minimum: 0
        unique_users_count:
          type: integer
          minimum: 0
          description: Omitted when group_by=user.
        users:
          type: array
          items:
            type: string
          description: Present when group_by=service and include_users=true.
        countries:
          type: array
          items:
            $ref: "#/components/schemas/CountryCount"
    CountryCount:
      type: object
      required: [country, request_count]
      properties:
        country:
          type: string
        request_count:
          type: integer
          minimum: 0
    MetricKey:
      type: string
      enum:
        - services-count
        - cpu-hours
        - gpu-hours
        - requests-sync-per-service
        - requests-async-per-service
        - requests-exposed-per-service
        - requests-per-user
        - users-per-service
        - countries-count
        - countries-list
    SourceStatus:
      type: object
      required: [name, status]
      properties:
        name:
          type: string
        status:
          type: string
          enum: [ok, partial, missing]
        last_updated:
          type: string
          format: date-time
        notes:
          type: string
