apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-secret
  namespace: oscar-svc
  annotations:
    serving.kserve.io/s3-endpoint: "minio.minio.svc.cluster.local:9000"
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-usevirtualbucket: "0"
    serving.kserve.io/s3-signature-version: "s3v4"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: Y2M1NWM1

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-sa
  namespace: oscar-svc
secrets:
  - name: minio-s3-secret
